SET client_encoding TO 'UTF8';

BEGIN;

CREATE TABLE IF NOT EXISTS Escala_Madurez (
    nivel SMALLINT PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL UNIQUE,
    CHECK (nivel BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS Niveles_Madurez_Control (
    control_id INT NOT NULL,
    nivel SMALLINT NOT NULL,
    descripcion TEXT NOT NULL,
    PRIMARY KEY (control_id, nivel),
    FOREIGN KEY (control_id) REFERENCES Controles(id) ON DELETE CASCADE,
    FOREIGN KEY (nivel) REFERENCES Escala_Madurez(nivel)
);

CREATE TABLE IF NOT EXISTS Madurez_Controles (
    id SERIAL PRIMARY KEY,
    cuestionario_id INT NOT NULL,
    control_id INT NOT NULL,
    nivel SMALLINT NOT NULL,
    FOREIGN KEY (cuestionario_id) REFERENCES Cuestionarios_Control_Interno(id),
    FOREIGN KEY (control_id) REFERENCES Controles(id),
    FOREIGN KEY (nivel) REFERENCES Escala_Madurez(nivel),
    UNIQUE (cuestionario_id, control_id)
);

INSERT INTO Escala_Madurez (nivel, nombre) VALUES
    (1, 'Inicial / Ad Hoc'),
    (2, 'Repetible pero Intuitivo'),
    (3, 'Definido'),
    (4, 'Administrado y Medible'),
    (5, 'Optimizado')
ON CONFLICT (nivel) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO Niveles_Madurez_Control (control_id, nivel, descripcion) VALUES
    ((SELECT id FROM Controles WHERE codigo = '8.2'), 1, 'Se reconoce que las cuentas administrativas necesitan control, pero su otorgamiento es reactivo y depende del criterio de cada administrador. No hay inventario de quién tiene privilegios ni medición alguna; ante un abuso la respuesta es impredecible y deriva en señalamientos personales porque las responsabilidades no son claras.'),
    ((SELECT id FROM Controles WHERE codigo = '8.2'), 2, 'La responsabilidad recae en un coordinador de seguridad con autoridad gerencial limitada. Los privilegios se otorgan siguiendo prácticas repetidas pero no documentadas y persisten cuentas genéricas compartidas (root, sa, sys); los sistemas registran el uso privilegiado, pero esa información no se analiza.'),
    ((SELECT id FROM Controles WHERE codigo = '8.2'), 3, 'Existe un procedimiento formal y documentado de solicitud, aprobación, emisión y revocación de cuentas privilegiadas, alineado con la política de seguridad de TI. Las responsabilidades están asignadas y entendidas, pero no se implementan de forma continua: las revisiones periódicas de privilegios se ejecutan de manera irregular.'),
    ((SELECT id FROM Controles WHERE codigo = '8.2'), 4, 'La identificación, autenticación y autorización de usuarios privilegiados está estandarizada y es obligatoria en todos los sistemas, incluidos los operados por terceros. Las revisiones de cuentas y privilegios siguen procesos formales y sus resultados se reportan ligados a objetivos del negocio; los indicadores están definidos (número de cuentas privilegiadas frente al personal autorizado, violaciones en la segregación de tareas) aunque todavía no se miden con constancia.'),
    ((SELECT id FROM Controles WHERE codigo = '8.2'), 5, 'El control de privilegios es responsabilidad conjunta del negocio y de la gerencia de TI, soportado por herramientas automatizadas que conceden acceso temporal y lo revocan al expirar. Toda actividad privilegiada se monitorea en registros que el propio administrador no puede alterar, y los KGIs/KPIs se recopilan, comunican y utilizan para ajustar el plan de seguridad en un proceso de mejora continua.'),

    ((SELECT id FROM Controles WHERE codigo = '8.5'), 1, 'Se reconoce la necesidad de autenticar a los usuarios, pero el mecanismo depende de cada sistema y de la iniciativa de quien lo administra. Las contraseñas se manejan de forma reactiva, no se mide su calidad y las brechas producen respuestas improvisadas.'),
    ((SELECT id FROM Controles WHERE codigo = '8.5'), 2, 'Un coordinador de seguridad define reglas básicas de contraseñas, pero las herramientas y las habilidades son inadecuadas y su aplicación está fraccionada. Los sistemas producen registros de intentos fallidos que nadie analiza, y los servicios de terceros pueden no cumplir los requerimientos de autenticación de la empresa.'),
    ((SELECT id FROM Controles WHERE codigo = '8.5'), 3, 'Existe un procedimiento definido de identificación única de todos los usuarios (internos, externos y temporales) alineado con la política de seguridad, y las identidades se mantienen en un repositorio central. Las responsabilidades están asignadas y entendidas pero no se implementan de forma continua, y la capacitación al usuario se comunica de manera informal.'),
    ((SELECT id FROM Controles WHERE codigo = '8.5'), 4, 'La identificación, autenticación y autorización de los usuarios está estandarizada en toda la organización, con autenticación reforzada obligatoria para acceder a los sistemas críticos. Los mecanismos se prueban mediante procesos estándares y formales que llevan a mejorar el nivel de seguridad; los indicadores ya están definidos pero aún no se miden.'),
    ((SELECT id FROM Controles WHERE codigo = '8.5'), 5, 'Los requerimientos de autenticación están definidos de forma clara e integrados con las aplicaciones desde la fase de diseño, como responsabilidad conjunta del negocio y de TI. Los intentos anómalos son atendidos de forma inmediata con procedimientos formales de respuesta soportados por herramientas automatizadas, y los KGIs/KPIs alimentan el ajuste continuo del plan de seguridad.'),

    ((SELECT id FROM Controles WHERE codigo = '8.13'), 1, 'La organización reconoce la necesidad de respaldar sus datos y existen procedimientos de respaldo y recuperación, pero no hay procedimientos implementados de comunicación formal ni capacitación específica. La responsabilidad sobre la administración de los datos no es clara.'),
    ((SELECT id FROM Controles WHERE codigo = '8.13'), 2, 'A lo largo de la organización existe conciencia sobre la necesidad de respaldar y las responsabilidades se asignan de manera informal a personal clave de TI. Se lleva a cabo algún monitoreo dentro de TI sobre respaldos y recuperación, y los requerimientos los documentan individuos clave, no la organización.'),
    ((SELECT id FROM Controles WHERE codigo = '8.13'), 3, 'Se asigna la propiedad de los datos a la parte responsable que controla su integridad y seguridad, y los procedimientos de respaldo y restauración se formalizan dentro de TI, alineados con el plan de continuidad. Se utilizan algunas herramientas, se realiza algún monitoreo y se definen métricas básicas de desempeño.'),
    ((SELECT id FROM Controles WHERE codigo = '8.13'), 4, 'Los procedimientos están formalizados y son ampliamente conocidos; el almacenamiento fuera de las instalaciones y las pruebas de restauración se ejecutan de forma regular y documentada. Los indicadores de desempeño y meta —porcentaje de restauraciones exitosas y oportunas, medios transferidos y almacenados de forma segura— se acuerdan y se monitorean mediante un proceso bien definido, con entrenamiento formal del personal.'),
    ((SELECT id FROM Controles WHERE codigo = '8.13'), 5, 'El respaldo se apoya en herramientas sofisticadas con un máximo de automatización y las necesidades futuras se exploran de manera proactiva. Los indicadores se ligan a los objetivos del negocio y se monitorean regularmente; las pruebas de recuperación son globales y sus resultados se utilizan para actualizar el plan de continuidad de forma permanente.'),

    ((SELECT id FROM Controles WHERE codigo = '8.24'), 1, 'Se reconoce la necesidad de cifrar cierta información, pero su uso es esporádico y depende de la iniciativa de quien administra cada sistema. No existen reglas sobre la generación ni la custodia de llaves y no se mide nada.'),
    ((SELECT id FROM Controles WHERE codigo = '8.24'), 2, 'Se emplea cifrado en algunos sistemas bajo prácticas repetidas pero no documentadas, y la administración de llaves depende de individuos concretos. Las herramientas y las habilidades son inadecuadas, y la pérdida o el compromiso de una llave no tiene un procedimiento previsto.'),
    ((SELECT id FROM Controles WHERE codigo = '8.24'), 3, 'Existe una política definida sobre el uso de criptografía y procedimientos documentados para generar, cambiar, revocar, destruir, distribuir, certificar, almacenar y archivar las llaves, alineados con la clasificación de la información. Las responsabilidades están asignadas y entendidas, pero no se implementan de forma continua.'),
    ((SELECT id FROM Controles WHERE codigo = '8.24'), 4, 'Los estándares, algoritmos y fortalezas aprobados están definidos y su cumplimiento es obligatorio; la protección de las llaves contra modificación y divulgación no autorizadas se verifica con procesos estándares y formales. Las actividades de administración de llaves se registran y auditan, y los indicadores están definidos aunque aún no se miden.'),
    ((SELECT id FROM Controles WHERE codigo = '8.24'), 5, 'Las funciones criptográficas están integradas con las aplicaciones desde la fase de diseño y su gestión está automatizada. Las llaves tienen fechas de activación y desactivación controladas, se realizan valoraciones periódicas para evaluar la efectividad del esquema, y los KGIs/KPIs se recopilan y comunican para ajustarlo de forma continua.'),

    ((SELECT id FROM Controles WHERE codigo = '8.15'), 1, 'Existen registros porque los sistemas los generan por omisión, no porque la organización lo haya decidido. Nadie los revisa, no se mide su cobertura y solo se consultan de forma reactiva después de un incidente.'),
    ((SELECT id FROM Controles WHERE codigo = '8.15'), 2, 'Se reconoce el valor de los registros y se activan en los sistemas más importantes, pero aunque producen información relevante respecto a la seguridad, ésta no se analiza. Los reportes son incompletos o engañosos y la retención depende del criterio de cada administrador.'),
    ((SELECT id FROM Controles WHERE codigo = '8.15'), 3, 'Está definido y documentado qué eventos se registran, dónde se almacenan y cuánto tiempo se conservan, alineado con la política de seguridad de TI. La revisión de los registros está asignada y se realiza, pero no de forma continua, y los reportes no contienen un enfoque claro de negocio.'),
    ((SELECT id FROM Controles WHERE codigo = '8.15'), 4, 'El registro y el monitoreo son obligatorios y estandarizados en todos los sistemas críticos, con los registros protegidos contra alteración por parte de los propios administradores. La detección de actividades inusuales o anormales sigue procesos formales, los reportes se ligan a los objetivos del negocio y los indicadores están definidos aunque aún no se miden.'),
    ((SELECT id FROM Controles WHERE codigo = '8.15'), 5, 'El monitoreo está centralizado y automatizado, correlacionando eventos de toda la organización, y los incidentes detectados disparan procedimientos formales de respuesta inmediata. La información sobre amenazas y vulnerabilidades se recolecta y analiza de manera sistemática, se realiza análisis de causa-efecto, y los KGIs/KPIs se recopilan y comunican para la mejora continua.'),

    ((SELECT id FROM Controles WHERE codigo = '8.32'), 1, 'Se reconoce que los cambios se deben administrar y controlar, pero las prácticas varían y es muy probable que se den cambios sin autorización. Hay documentación de cambio pobre o inexistente y ocurren errores e interrupciones en el ambiente de producción provocados por una pobre administración de cambios.'),
    ((SELECT id FROM Controles WHERE codigo = '8.32'), 2, 'Existe un proceso informal que la mayoría de los cambios sigue, pero no está estructurado, es rudimentario y propenso a errores. La exactitud de la documentación de configuración es inconsistente, la planeación es limitada y la evaluación de impacto se da de forma superficial previa al cambio.'),
    ((SELECT id FROM Controles WHERE codigo = '8.32'), 3, 'Existe un proceso formal definido que incluye categorización, asignación de prioridades, procedimientos de emergencia, autorización del cambio y administración de liberación. Aún se dan soluciones temporales, el proceso a menudo se omite o se hace a un lado, y los cambios no autorizados ocurren ocasionalmente.'),
    ((SELECT id FROM Controles WHERE codigo = '8.32'), 4, 'El proceso está bien desarrollado y es consistente para todos los cambios, y la gerencia confía en que hay excepciones mínimas. Todos los cambios pasan por planeación minuciosa, evaluación de impacto y un proceso de aprobación; la documentación es vigente y correcta con seguimiento formal, y existe un proceso consistente para monitorear la calidad y el desempeño de la gestión de cambios.'),
    ((SELECT id FROM Controles WHERE codigo = '8.32'), 5, 'El proceso se revisa con regularidad y se actualiza para permanecer en línea con las buenas prácticas, reflejando los resultados del monitoreo. La información de configuración está computarizada y proporciona control de versiones, el rastreo del cambio es sofisticado e incluye herramientas para detectar software no autorizado, y la administración de cambio de TI se integra con la del negocio.'),

    ((SELECT id FROM Controles WHERE codigo = '8.31'), 1, 'Existe la percepción de la necesidad de verificar que lo implantado sirve para el propósito esperado, pero las pruebas se realizan solo en algunos proyectos y el enfoque lo decide cada equipo. Es habitual probar sobre producción y la acreditación formal y la autorización son raras o inexistentes.'),
    ((SELECT id FROM Controles WHERE codigo = '8.31'), 2, 'Existe cierta consistencia entre los enfoques de prueba, pero no se basan en ninguna metodología y los equipos individuales deciden el suyo. Puede haber un entorno separado, pero se levanta de forma ad hoc, sin datos representativos, con ausencia de pruebas de integración y un proceso de aprobación informal.'),
    ((SELECT id FROM Controles WHERE codigo = '8.31'), 3, 'Se cuenta con una metodología formal de instalación, migración, conversión y aceptación, integrada dentro del ciclo de vida del sistema y automatizada hasta cierto punto. Los entornos están separados, pero la calidad de los sistemas que pasan a producción es inconsistente porque la transición varía según decisiones individuales.'),
    ((SELECT id FROM Controles WHERE codigo = '8.31'), 4, 'Los procedimientos son formales, con ambientes de prueba definidos y procedimientos de acreditación, y todos los cambios mayores siguen ese enfoque. El sistema de prueba refleja adecuadamente el ambiente de producción —incluidos los gestores de base de datos— con datos desinfectados, y se aplican pruebas de stress y de regresión en los proyectos mayores.'),
    ((SELECT id FROM Controles WHERE codigo = '8.31'), 5, 'Los ambientes de prueba están bien desarrollados y totalmente integrados dentro del ciclo de vida del sistema, automatizados cuando es apropiado, asegurando una transición eficiente y efectiva al ambiente de producción sin repetición de trabajos. Las revisiones posteriores a la implantación son estándar y las lecciones aprendidas se canalizan nuevamente hacia el proceso.'),

    ((SELECT id FROM Controles WHERE codigo = '8.12'), 1, 'La organización reconoce que ciertos datos son sensibles y hay algún método para especificar requerimientos de seguridad, pero no hay procedimientos implementados de comunicación formal sobre cómo protegerlos en su recibo, procesamiento, almacenamiento y salida. La responsabilidad no es clara y no se imparte capacitación.'),
    ((SELECT id FROM Controles WHERE codigo = '8.12'), 2, 'Existe conciencia en toda la organización y a alto nivel empieza a observarse la propiedad sobre los datos. Los requerimientos de seguridad para la administración de datos son documentados por individuos clave y se monitorean informalmente algunas actividades, como el desecho de medios.'),
    ((SELECT id FROM Controles WHERE codigo = '8.12'), 3, 'Se asigna la propiedad de los datos a la parte responsable que controla su integridad y seguridad, y existen políticas documentadas de clasificación y uso aceptable. Se aplican algunos controles a la salida de la información y se definen métricas básicas de desempeño, aunque el monitoreo es parcial.'),
    ((SELECT id FROM Controles WHERE codigo = '8.12'), 4, 'Los procedimientos de protección de datos sensibles están formalizados, son ampliamente conocidos y de cumplimiento obligatorio, apoyados en herramientas. Los indicadores de desempeño y meta se acuerdan y se monitorean mediante un proceso bien definido, y las violaciones y desviaciones se reportan al negocio.'),
    ((SELECT id FROM Controles WHERE codigo = '8.12'), 5, 'La protección de la información está automatizada con herramientas sofisticadas que cubren todo el ciclo de vida del dato y las necesidades futuras se exploran de manera proactiva. Los indicadores se ligan a los objetivos del negocio, se monitorean regularmente y se exploran constantemente oportunidades de mejora.'),

    ((SELECT id FROM Controles WHERE codigo = '8.20'), 1, 'Se reconoce la necesidad de proteger la red, pero las medidas se aplican de forma reactiva tras un incidente y dependen del conocimiento de quien administra los equipos. No se mide la exposición ni existen reglas documentadas.'),
    ((SELECT id FROM Controles WHERE codigo = '8.20'), 2, 'Hay firewalls y algún control perimetral operando bajo prácticas repetidas pero no documentadas. Los dispositivos producen información relevante que no se analiza, y los servicios de terceros pueden no cumplir los requerimientos de conectividad de la empresa.'),
    ((SELECT id FROM Controles WHERE codigo = '8.20'), 3, 'Existen procedimientos definidos de segmentación, reglas de filtrado y autorización de accesos a la red, alineados con la política de seguridad de TI y motivados por un análisis de riesgo. Se realizan pruebas de seguridad adecuadas, por ejemplo pruebas contra intrusos, pero se programan y comunican de manera informal.'),
    ((SELECT id FROM Controles WHERE codigo = '8.20'), 4, 'La configuración segura de los equipos de red y el control de los flujos de información están estandarizados y su cumplimiento es obligatorio. Las pruebas de penetración y de seguridad del sistema se hacen utilizando procesos estándares y formales que llevan a mejorar los niveles de seguridad, y los indicadores están definidos aunque aún no se miden.'),
    ((SELECT id FROM Controles WHERE codigo = '8.20'), 5, 'La detección de intrusos y el control de la red están integrados a lo largo de toda la organización y coordinados con la función de seguridad corporativa. La información sobre amenazas y vulnerabilidades de red se recolecta y analiza de manera sistemática, y los KGIs/KPIs se utilizan para ajustar el plan de seguridad en un proceso de mejora continua.'),

    ((SELECT id FROM Controles WHERE codigo = '8.7'), 1, 'Se reconoce el riesgo del software malicioso y hay antivirus instalado en algunos equipos por iniciativa individual. La actualización es irregular, no se mide la cobertura y la respuesta ante una infección es improvisada.'),
    ((SELECT id FROM Controles WHERE codigo = '8.7'), 2, 'Existe una solución antimalware desplegada en la mayoría de los equipos bajo prácticas repetidas pero no documentadas. Los sistemas generan alertas que no se analizan de forma sistemática y la concientización del usuario depende principalmente de su propia iniciativa.'),
    ((SELECT id FROM Controles WHERE codigo = '8.7'), 3, 'Están definidos y documentados los procedimientos de prevención, detección y corrección, incluida la aplicación de parches de seguridad y la actualización del control de virus, alineados con la política de seguridad de TI. Existe capacitación para TI y para el negocio, pero se programa y se comunica de manera informal.'),
    ((SELECT id FROM Controles WHERE codigo = '8.7'), 4, 'La distribución del software de protección es centralizada y su nivel de versión y parche se administra mediante la gestión de configuración y de cambios de TI. La concientización del usuario es obligatoria, los servidores de base de datos están cubiertos con exclusiones justificadas y documentadas, y los indicadores están definidos aunque aún no se miden.'),
    ((SELECT id FROM Controles WHERE codigo = '8.7'), 5, 'La protección está integrada a lo largo de toda la organización, con respuesta automatizada ante detecciones y filtrado del tráfico entrante de correo y descargas. La información sobre nuevas amenazas se recolecta y analiza de manera sistemática, se realiza análisis de causa-efecto de cada incidente, y los KGIs/KPIs se recopilan y comunican para la mejora continua.')
ON CONFLICT (control_id, nivel) DO UPDATE SET descripcion = EXCLUDED.descripcion;

COMMIT;
